### ISSUE TITLE
Drupal 8.8.0 : TypeError: Argument 2 passed to Drupal\page_cache\StackMiddleware\PageCache::storeResponse()

### ISSUE THREAD

**Issue by Marek-Zientek** [litespeedtech/lscache-drupal#12] opened 2020-03-10 15:38 UTC
When I try to log in I get the following message:
The website encountered an unexpected error. Please try again later.
TypeError: Argument 2 passed to Drupal\page_cache\StackMiddleware\PageCache::storeResponse() must be an instance of Symfony\Component\HttpFoundation\Response, null given, called in /home/naukispo/domains/nauki-spoleczne.info/public_html/core/modules/page_cache/src/StackMiddleware/PageCache.php on line 195 in Drupal\page_cache\StackMiddleware\PageCache->storeResponse() (line 212 of core/modules/page_cache/src/StackMiddleware/PageCache.php).

I use litespeed and memcached.

**Comment by lupupitkanen** [comment] 2020-06-02 23:49
That error is from the Internal Page Cache module (page-cache), not from lscache module.

I think you should disable the internal page cache module if you are using the LSCache module.

**Comment by lupupitkanen** [comment] 2020-08-25 12:23
I'm quite sure this is a duplicate of #10 and should be closed.

**Comment by Woet** [comment] 2020-09-17 14:56
Duplicate of #10

**Closed by Woet** 2020-09-17 14:56 UTC
